<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Added to Cart_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>706070df-cae4-46ba-9342-1158305e9bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a627927-ad45-4c62-b549-74df9347b2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>366fe45a-cb1b-4a1f-b26e-b2f33653ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>abb5fef1-d3fa-462c-8b32-64abae76c7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;B0CTD3VBM2&quot;,&quot;B00ADBY98A&quot;,&quot;B08WM3LMJF&quot;]</value>
      <webElementGuid>e57a0a48-3402-43f3-be1f-35ac99dab532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>0bb47930-e964-4bac-bb02-bed420c20a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>558993f1-be63-4576-a062-cfc361277c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>pd_day0fbt_hardlines_crt</value>
      <webElementGuid>417cd86a-ac5a-4ed6-9ff8-d56621960860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=pd_day0fbt_hardlines_crt?_encoding=UTF8&amp;pd_rd_w=3Ix39&amp;content-id=amzn1.sym.3343bdc6-9855-4dad-ae6a-60a908a293a7&amp;pf_rd_p=3343bdc6-9855-4dad-ae6a-60a908a293a7&amp;pf_rd_r=MP0Y00V8SA2ANQR279AA&amp;pd_rd_wg=4CqFA&amp;pd_rd_r=a0b5b3c8-7b20-4b15-ad6b-6c0000d87819</value>
      <webElementGuid>6949b699-2726-4a04-a7f5-e4ce33d53b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>b1b818bb-4c24-4a33-84b7-cd620ea025d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-10-announce</value>
      <webElementGuid>2f52b664-1255-4960-b674-4c2d2d15ebb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-10&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>301f53eb-6714-4a91-8b9b-d4f5a36110ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>f8355d69-d075-4ca6-9958-635a031c7835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-10']/span/input</value>
      <webElementGuid>0d3da1af-eae3-49b0-8327-0faa07113fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/input</value>
      <webElementGuid>b458ad84-92aa-49a4-9d0f-7a11053f1589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>dbccbe5e-bf6e-4397-90c3-b8b42a2e88d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
