<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sign Out_hm-icon nav-sprite</name>
   <tag></tag>
   <elementGuidId>8c1b2d9d-b17a-416d-b488-974df7aea83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.hm-icon.nav-sprite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1ddf93c4-b47e-4f9e-958b-8d7b48b91786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hm-icon nav-sprite</value>
      <webElementGuid>74fc019c-39c9-4d4f-a5f6-f7375893e326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)/i[@class=&quot;hm-icon nav-sprite&quot;]</value>
      <webElementGuid>07d9dc2c-14ae-468c-b0c4-046b129f711c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']/i</value>
      <webElementGuid>dcac8dc2-8e00-48e3-ae16-a03566d02356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>a1efe9d3-1011-4f25-9e92-e7c0f02ca215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
